#!/usr/bin/env python3
"""
Generate Sentinel Destination "source routes" from Microsoft's own published connectors.

Why
---
Abstract sends each event with the vendor's raw record in `event.original` plus a few
routing fields (vendor, product, data_stream.dataset, timestamps). Microsoft's Content Hub
connectors already contain the parsing that turns that vendor's raw record into the
vendor's Sentinel table: each publishes a Data Collection Rule whose input stream is the
vendor's raw API shape and whose transformKql maps it into the table the solution's
parsers, analytics rules and workbooks read.

This script reuses that parsing unchanged. For each source listed in
parameters/sentinel-source-routes.json it reads the connector's published DCR (and, for a
custom `_CL` target, its table definition) from github.com/Azure/Azure-Sentinel at a
PINNED commit, and emits one DCR dataflow that:

  1. selects that source's events from the Abstract stream (a KQL condition on the
     routing fields),
  2. unpacks `event.original` into exactly the columns Microsoft's input stream declares,
     filling any column Microsoft's own poller adds (for example Okta's DomainName) from
     the source's `defaults`, then
  3. runs Microsoft's published transformKql, with its one reference to `source` pointed
     at step 2.

Output: parameters/sentinel-source-routes.generated.json, loaded by the Sentinel
Destination templates, and the source list in both templates' portal forms. A source is
only deployed when the customer selects it (`sourceRoutes`).

Each portal form sits next to its template (X.createUiDefinition.json, X.bicep,
X.azuredeploy.json). The compiled ARM template embeds the generated routes, so a new
source is only deployable once the ARM is rebuilt: this script rebuilds it with
`az bicep build`, and --check fails when a form or template is missing or the ARM does not
embed the current routes. Otherwise the portal would offer a source whose route the
template silently skips.

Licensing: Azure/Azure-Sentinel is MIT-licensed (Copyright (c) Microsoft Corporation).
Each generated route carries that notice and its exact source path and commit.

Run with --check in CI (exits 1 when the committed output is stale). Needs network access
to raw.githubusercontent.com, or --repo <local clone of Azure-Sentinel>.
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

RAW = "https://raw.githubusercontent.com/Azure/Azure-Sentinel/{ref}/{path}"
TRANSFORM_LIMIT = 15360          # Azure Monitor: characters per transformKql
SOURCE_REF = re.compile(r"(^|[;\n]\s*)source\b")

CAST = {"string": "tostring", "datetime": "todatetime", "int": "toint", "long": "tolong",
        "real": "toreal", "boolean": "tobool", "guid": "tostring"}


def fetch(ref, path, repo):
    if repo:
        return (Path(repo) / path).read_text(encoding="utf-8")
    url = RAW.format(ref=ref, path=urllib.parse.quote(path))
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def find(obj, test):
    if isinstance(obj, dict):
        if test(obj):
            return obj
        for value in obj.values():
            hit = find(value, test)
            if hit is not None:
                return hit
    elif isinstance(obj, list):
        for value in obj:
            hit = find(value, test)
            if hit is not None:
                return hit
    return None


GENERATED_MARK = "Generated by gen-sentinel-source-routes.py"


def embedded_routes(arm_doc):
    """The generated routes document as `az bicep build` inlined it into the ARM template."""
    return find(arm_doc, lambda o: isinstance(o.get("description"), str)
                and o["description"].startswith(GENERATED_MARK) and "routes" in o)


def build_route(source, ref, repo):
    dcr_doc = json.loads(fetch(ref, source["connector"]["dcr"], repo))
    dcr = find(dcr_doc, lambda o: "streamDeclarations" in o and "dataFlows" in o)
    if dcr is None:
        raise ValueError(f"{source['name']}: no DCR with streamDeclarations in {source['connector']['dcr']}")
    flows = dcr["dataFlows"]
    flow = next((f for f in flows if f.get("outputStream") == source.get("outputStream")), None) \
        if source.get("outputStream") else (flows[0] if len(flows) == 1 else None)
    if flow is None:
        raise ValueError(f"{source['name']}: DCR has {len(flows)} dataflows; set outputStream to pick one")
    stream = flow["streams"][0]
    columns = dcr["streamDeclarations"][stream]["columns"]
    published = flow.get("transformKql") or "source"

    defaults = source.get("defaults", {})
    projected = []
    for column in columns:
        name, kind = column["name"], column["type"].lower()
        if name in defaults:
            projected.append(f"{name} = {json.dumps(defaults[name])}" if kind == "string"
                             else f"{name} = {CAST.get(kind, 'tostring')}({json.dumps(defaults[name])})")
        elif kind == "dynamic":
            projected.append(f"{name} = r['{name}']")
        else:
            projected.append(f"{name} = {CAST.get(kind, 'tostring')}(r['{name}'])")

    matches = list(SOURCE_REF.finditer(published))
    if len(matches) != 1:
        raise ValueError(f"{source['name']}: expected exactly one table reference to `source` in the "
                         f"published transform, found {len(matches)}; review it by hand")
    body = SOURCE_REF.sub(lambda m: m.group(1) + "abstractSource", published, count=1)
    transform = ("let abstractSource = source\n"
                 f"| where {source['match']} and isnotempty(tostring(event.original))\n"
                 "| extend r = parse_json(tostring(event.original))\n"
                 "| project " + ", ".join(projected) + ";\n" + body)
    if len(transform) > TRANSFORM_LIMIT:
        raise ValueError(f"{source['name']}: transform is {len(transform)} characters, over the "
                         f"{TRANSFORM_LIMIT} Azure limit")

    route = {"name": source["name"], "outputStream": flow["outputStream"], "transformKql": transform,
             "provenance": {"repository": "Azure/Azure-Sentinel", "license": "MIT", "ref": ref,
                            "dcr": source["connector"]["dcr"], "inputStream": stream,
                            "rawColumns": [c["name"] for c in columns]}}

    table_path = source["connector"].get("tables")
    if flow["outputStream"].startswith("Custom-"):
        if not table_path:
            raise ValueError(f"{source['name']}: output is a custom table; set connector.tables")
        table_doc = json.loads(fetch(ref, table_path, repo))
        table_name = flow["outputStream"][len("Custom-"):]
        schema = find(table_doc, lambda o: isinstance(o.get("schema"), dict)
                      and o["schema"].get("name") == table_name and "columns" in o["schema"])
        if schema is None:
            raise ValueError(f"{source['name']}: no schema for {table_name} in {table_path}")
        route["table"] = {"name": table_name,
                          "columns": [{"name": c["name"], "type": c["type"]} for c in schema["schema"]["columns"]]}
        route["provenance"]["tables"] = table_path
    return route


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="solutions/parameters/sentinel-source-routes.json")
    parser.add_argument("--out", default="solutions/parameters/sentinel-source-routes.generated.json")
    parser.add_argument("--repo", help="Local clone of Azure-Sentinel (defaults to GitHub at the pinned ref)")
    parser.add_argument("--ui", nargs="*", default=[
        "solutions/templates/destinations/sentinel-destination.createUiDefinition.json",
        "solutions/templates/destinations/sentinel-destination-with-app.createUiDefinition.json"],
        help="Portal forms whose sourceRoutes options are kept in sync with the source list")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    config = json.loads(Path(args.config).read_text(encoding="utf-8"))
    try:
        routes = [build_route(s, config["ref"], args.repo) for s in config["sources"]]
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        parser.error(str(error))
    output = json.dumps({"description": "Generated by gen-sentinel-source-routes.py from Microsoft's "
                                        "published Sentinel connectors. Do not edit by hand.",
                         "license": "Transformations are from github.com/Azure/Azure-Sentinel, MIT License, "
                                    "Copyright (c) Microsoft Corporation.",
                         "ref": config["ref"], "routes": routes}, indent=2) + "\n"
    options = [{"label": s.get("label", s["name"]), "value": s["name"]} for s in config["sources"]]
    stale = []
    target = Path(args.out)
    if not target.is_file() or target.read_text(encoding="utf-8") != output:
        stale.append(args.out)
    ui_updates = {}
    missing = []
    for ui in args.ui:
        path = Path(ui)
        if not path.is_file():
            missing.append(ui)
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        element = find(doc, lambda o: o.get("name") == "sourceRoutes" and "constraints" in o)
        if element is None:
            missing.append(f"{ui} (no sourceRoutes element)")
            continue
        if element["constraints"].get("allowedValues") != options:
            element["constraints"]["allowedValues"] = options
            ui_updates[path] = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
            stale.append(ui)
    expected = json.loads(output)
    arm_stale = []
    for ui in args.ui:
        arm = Path(ui.replace(".createUiDefinition.json", ".azuredeploy.json"))
        if not arm.is_file():
            missing.append(str(arm))
            continue
        if embedded_routes(json.loads(arm.read_text(encoding="utf-8"))) != expected:
            arm_stale.append(arm)
    if missing:
        print("missing (fix --ui or restore the file): " + ", ".join(missing), file=sys.stderr)
        sys.exit(1)
    if args.check:
        stale += [str(a) for a in arm_stale]
        if stale:
            print("stale (run solutions/scripts/gen-sentinel-source-routes.py): " + ", ".join(stale), file=sys.stderr)
            sys.exit(1)
        print(f"sentinel source routes current: {len(routes)} route(s)")
        return
    target.write_text(output, encoding="utf-8")
    for path, text in ui_updates.items():
        path.write_text(text, encoding="utf-8")
    for arm in arm_stale:
        bicep = arm.with_name(arm.name.replace(".azuredeploy.json", ".bicep"))
        if not shutil.which("az"):
            print(f"rebuild {arm}: az bicep build --file {bicep} --outfile {arm}", file=sys.stderr)
            sys.exit(1)
        subprocess.run(["az", "bicep", "build", "--file", str(bicep), "--outfile", str(arm)], check=True)
        if embedded_routes(json.loads(arm.read_text(encoding="utf-8"))) != expected:
            print(f"{arm}: rebuilt but does not embed the generated routes; check {bicep} loads them", file=sys.stderr)
            sys.exit(1)
        print(f"rebuilt {arm}")
    for route in routes:
        print(f"{route['name']}: -> {route['outputStream']} ({len(route['transformKql'])} chars)")


if __name__ == "__main__":
    main()
