#!/usr/bin/env python3
"""
Generate the Sentinel Destination's ASIM routes from solutions/asim/*.kql.

Why
---
Abstract already normalizes every source into the Abstract Common Schema (ACS). Each
file in solutions/asim/ maps ACS into one of Microsoft's ASIM normalized tables
(ASimAuthenticationEventLogs, ASimNetworkSessionLogs, ...). Microsoft's built-in ASIM
unifying parsers read those tables, so Microsoft's ASIM analytics rules, hunting
queries and workbooks work on Abstract data from any vendor. One mapping per schema,
keyed on ACS: a new vendor needs nothing here.

Each .kql file starts with comment lines; `// outputStream: Microsoft-ASim...` names
the target. The generator strips the comments and emits
solutions/parameters/sentinel-asim-routes.generated.json, loaded by the Sentinel
Destination templates as one DCR dataflow per enabled schema. It keeps the templates'
portal forms (the asimSchemas list) in sync, rebuilds the compiled ARM templates with
`az bicep build`, and --check fails when any of them lags. Transformations must stay
under Azure's 15,360-character limit.
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

TRANSFORM_LIMIT = 15360
MARK = "Generated by gen-sentinel-asim.py"
OUTPUT = re.compile(r"^//\s*outputStream:\s*(Microsoft-ASim\w+)\s*$", re.M)
SCHEMA = re.compile(r"^//\s*ASIM schema:\s*(\w+)", re.M)


def find(obj, test):
    if isinstance(obj, dict):
        if test(obj):
            return obj
        obj = list(obj.values())
    if isinstance(obj, list):
        for value in obj:
            hit = find(value, test)
            if hit is not None:
                return hit
    return None


# Scalar functions and operators Azure Monitor transformations accept (learn.microsoft.com:
# azure-monitor/data-collection/data-collection-transformations-kql). Anything else
# compiles in Log Analytics but fails the DCR deploy, so it is refused here.
ALLOWED_FUNCTIONS = set("""
tobool todatetime todouble toreal toguid toint tolong tostring totimespan ago datetime_add datetime_diff
datetime_part dayofmonth dayofweek dayofyear endofday endofmonth endofweek endofyear getmonth monthofyear
getyear hourofday make_datetime make_timespan now startofday startofmonth startofweek startofyear weekofyear
array_concat array_length pack pack_array parse_json parse_xml zip abs bin floor ceiling exp exp10 exp2
isfinite isinf isnan log log10 log2 pow round sign case iif max_of min_of base64_encodestring
base64_decodestring countof extract extract_all indexof isempty isnotempty replace split strcat strcat_delim
strlen substring tolower toupper hash_sha256 gettype isnotnull isnull columnifexists geo_location
parse_cef_dictionary not and or in where project extend print binary_and binary_or binary_xor binary_not binary_shift_left binary_shift_right
""".split())
REFUSED_OPERATORS = ["has_any", "has_all", "in~", "!in~", "coalesce", "bag_pack", "column_ifexists"]


def lint(path, kql):
    code = re.sub(r"'(?:[^'\\]|\\.)*'", "''", kql)
    problems = sorted({m for m in re.findall(r"\b([a-z_][a-z0-9_]*)\s*\(", code) if m not in ALLOWED_FUNCTIONS})
    problems += [op for op in REFUSED_OPERATORS if re.search(r"(?<![\w!])" + re.escape(op) + r"(?![\w~])", code)]
    if problems:
        raise ValueError(f"{path}: not supported in Azure Monitor transformations: {', '.join(sorted(set(problems)))}")


KQL_TYPES = {"string": "string", "int": "int", "long": "long", "real": "real", "bool": "bool",
             "boolean": "bool", "datetime": "datetime", "dynamic": "dynamic", "guid": "guid"}


def check_columns(path, kql, table):
    """Every column the mapping projects must exist in Microsoft's table: Azure drops unknown
    columns silently (ColumnsDroppedCount), so a typo would look like missing data."""
    spec = path.parent / "tables" / f"{table}.json"
    if not spec.is_file():
        raise ValueError(f"{path}: no column list at {spec}; capture it from a Sentinel workspace")
    known = {c["name"] for c in json.loads(spec.read_text(encoding="utf-8"))["columns"]}
    block = kql.split("| project", 1)[1] if "| project" in kql else ""
    projected = re.findall(r"^\s{4}(\w+)\s*=", block, re.M)
    if not projected:
        raise ValueError(f"{path}: no `| project` block with one `Column = expression` per line")
    unknown = sorted(set(projected) - known)
    if unknown:
        raise ValueError(f"{path}: not columns of {table}: {', '.join(unknown)}")
    dupes = sorted({c for c in projected if projected.count(c) > 1})
    if dupes:
        raise ValueError(f"{path}: projected twice: {', '.join(dupes)}")


def build(path):
    text = path.read_text(encoding="utf-8")
    output, schema = OUTPUT.search(text), SCHEMA.search(text)
    if not output or not schema:
        raise ValueError(f"{path}: needs '// ASIM schema: <Name>' and '// outputStream: Microsoft-ASim<Table>' lines")
    kql = "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("//")).strip()
    if not kql.startswith("source"):
        raise ValueError(f"{path}: the transformation must start from `source`")
    lint(path, kql)
    check_columns(path, kql, output.group(1)[len("Microsoft-"):])
    if len(kql) > TRANSFORM_LIMIT:
        raise ValueError(f"{path}: {len(kql)} characters, over Azure's {TRANSFORM_LIMIT} limit")
    return {"name": schema.group(1), "outputStream": output.group(1),
            "table": output.group(1)[len("Microsoft-"):], "transformKql": kql,
            "source": str(path.as_posix())}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--asim", default="solutions/asim")
    parser.add_argument("--out", default="solutions/parameters/sentinel-asim-routes.generated.json")
    parser.add_argument("--ui", nargs="*", default=[
        "solutions/templates/destinations/sentinel-destination.createUiDefinition.json",
        "solutions/templates/destinations/sentinel-destination-with-app.createUiDefinition.json"],
        help="Portal forms (each beside its .bicep and .azuredeploy.json) kept in sync with the schema list")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        routes = [build(p) for p in sorted(Path(args.asim).glob("*.kql"))]
    except (OSError, ValueError) as error:
        parser.error(str(error))
    if not routes:
        parser.error(f"no .kql files in {args.asim}")
    for route in routes:
        route["source"] = route["source"].split("/")[-1]
    output = json.dumps({"description": f"{MARK} from the ACS-to-ASIM mappings in solutions/asim. Do not edit by hand.",
                         "routes": routes}, indent=2) + "\n"
    expected = json.loads(output)
    options = [{"label": r["name"], "value": r["name"]} for r in routes]

    stale, missing, ui_updates, arm_stale = [], [], {}, []
    target = Path(args.out)
    if not target.is_file() or target.read_text(encoding="utf-8") != output:
        stale.append(args.out)
    for ui in args.ui:
        path, arm = Path(ui), Path(ui.replace(".createUiDefinition.json", ".azuredeploy.json"))
        if not path.is_file() or not arm.is_file():
            missing += [str(p) for p in (path, arm) if not p.is_file()]
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        element = find(doc, lambda o: o.get("name") == "asimSchemas" and "constraints" in o)
        if element is None:
            missing.append(f"{ui} (no asimSchemas element)")
            continue
        if element["constraints"].get("allowedValues") != options:
            element["constraints"]["allowedValues"] = options
            element["defaultValue"] = [o["label"] for o in options]
            ui_updates[path] = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
            stale.append(ui)
        embedded = find(json.loads(arm.read_text(encoding="utf-8")),
                        lambda o: isinstance(o.get("description"), str) and o["description"].startswith(MARK))
        if embedded != expected:
            arm_stale.append(arm)
    if missing:
        print("missing (fix --ui or restore the file): " + ", ".join(missing), file=sys.stderr)
        sys.exit(1)
    if args.check:
        stale += [str(a) for a in arm_stale]
        if stale:
            print("stale (run solutions/scripts/gen-sentinel-asim.py): " + ", ".join(stale), file=sys.stderr)
            sys.exit(1)
        print(f"sentinel ASIM routes current: {len(routes)} schema(s)")
        return
    target.write_text(output, encoding="utf-8")
    for path, text in ui_updates.items():
        path.write_text(text, encoding="utf-8")
    for arm in arm_stale:
        bicep = arm.with_name(arm.name.replace(".azuredeploy.json", ".bicep"))
        if not shutil.which("az"):
            print(f"rebuild {arm}: az bicep build --file {bicep} --outfile {arm}", file=sys.stderr)
            sys.exit(1)
        subprocess.run(["az", "bicep", "build", "--file", str(bicep), "--outfile", str(arm)], check=True)
        print(f"rebuilt {arm}")
    for route in routes:
        print(f"{route['name']}: -> {route['outputStream']} ({len(route['transformKql'])} chars)")


if __name__ == "__main__":
    main()
